services:
  database:
    image: 'postgres:16.0-alpine3.18'
    env_file:
      - ../.env
    ports:
      - "5432:5432"




# psql --host=localhost --username=postgres --port=5432
# Subir o docke de acordo com a pasta que ele est√°
# docker compose -f infra/compose.yaml up -d